##############################################################################
##
## Author:      Jamie E. Simon (modified)
##
## Description: 
##
##############################################################################

## Import modulues
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.lines as mlines



def plot_storageloss_curves(A_i, B_i = None, a_T = 1.0, logscale = True, 
                                    fontsize_plot = 13, markersize_plot = 12, labelsize_plot = 12, 
                                    extra_stuff = False, picture_name = 'StorageLossCurve.png'):
    # Set markers
    markers = ['o', '^', 'x', 's', 'P', 'h']
    
    # Design list
    list_names = ['$\mathrm{T}_1$','$\mathrm{T}_2$','$\mathrm{T}_3$','$\mathrm{T}_4$','$\mathrm{T}_5$','$\mathrm{T}_6$']
    
    # name list
    target_l = ["E'", "E''"]

    ## Get all unique temperatures
    temp_unique = np.unique(A_i[:,0])
    
    ## Set data
    Z, X, Ys, Yl  = A_i[:,0], A_i[:,1], A_i[:,2], A_i[:,3]
    
    ## Plot storage and loss modulus
    fig,axes = plt.subplots(1,2,figsize = (12,7), tight_layout = True)
    
    ## Plot shifted data
    for i in range(0,len(temp_unique)):
        x, ys, yl = X[Z == temp_unique[i]], Ys[Z == temp_unique[i]], Yl[Z == temp_unique[i]]
        axes[0].plot(x,ys,marker=markers[i],color='black',linestyle='-',markersize=markersize_plot)
        axes[1].plot(x,yl,marker=markers[i],color='black',linestyle='-',markersize=markersize_plot)
    
    
    ## Michs....
    for i in range(0,len(axes)):
        axes[i].set_xlabel('$\omega$ [rad/s]',fontsize=fontsize_plot)
        axes[i].set_ylabel(target_l[i],fontsize=fontsize_plot)
        axes[i].tick_params(axis='both', which='major', labelsize=labelsize_plot)
        axes[i].grid('on')
        if logscale == True:
            axes[i].set_xscale('log')
            
    if extra_stuff == True:
        # Create proxy handles for the legend (invisible lines with markers)
        proxy_handles = [mlines.Line2D([], [], color='black', marker=marker, linestyle='None', markersize=8)
                     for marker in markers]

        # Manually create the legend with unique temperature labels
        fig.legend(proxy_handles, list_names, loc='upper center', 
                   ncol=6, bbox_to_anchor=(0.50, 1.08), fontsize=12,frameon=True)

        # Adjust layout to create space for the legend box
        plt.subplots_adjust(top=0.85)
    
        # Save figure
        plt.savefig(picture_name, bbox_inches="tight")
        
    plt.show()
    return

def plot_mastercurve(A_i, B_i = None, a_T = 1.0, logscale = True, 
                                    fontsize_plot = 13, markersize_plot = 12, labelsize_plot = 12, 
                                    extra_stuff = False, picture_name = 'MasterCurve.png'):
    
    """
    input:
        A_i numpy array N x M: containing output data generated by local optimization routine
        B_i numpy array L x K: containing DMTA temperatures and shift-factors
    """
    
    # Set markers
    markers = ['o', '^', 'x', 's', 'P', 'h']
    
    # Design list
    list_names = ['$\mathrm{T}_1$','$\mathrm{T}_2$','$\mathrm{T}_3$','$\mathrm{T}_4$','$\mathrm{T}_5$','$\mathrm{T}_6$']

    ## Get all unique temperatures
    temp_unique = np.unique(A_i[:,0])
    
    ## Set data
    Z, X, Y, Xs  = A_i[:,0], A_i[:,1], A_i[:,2], A_i[:,3]

    ## Set figure
    fig,axes = plt.subplots(1,1,figsize = (12,7), tight_layout = True)
    
    ## Plot shifted data
    for i in range(0,len(temp_unique)):
        x, y = Xs[Z==temp_unique[i]], Y[Z==temp_unique[i]]
        axes.plot(x*a_T,y,marker=markers[i],color='black',markersize = markersize_plot)
    axes.plot(x*a_T,y,marker='none',color='black', label='Shifted data')
    
    ## Plot unshifted data
    for i in range(0,len(temp_unique)):
        x, y = X[Z==temp_unique[i]], Y[Z==temp_unique[i]]
        axes.plot(x*a_T,y,marker=markers[i],color='red',markersize = markersize_plot)
    axes.plot(x*a_T,y,marker='none',color='red', label='Non-shifted data')

    ## Michs....        
    axes.set_xlabel('$\omega$ [rad/s]',fontsize=fontsize_plot)
    axes.set_ylabel("$E'$ [MPa]",fontsize=fontsize_plot)
    axes.tick_params(axis='both', which='major', labelsize=labelsize_plot)
    axes.legend(loc='best', fontsize=fontsize_plot)
    axes.grid('on')
    if logscale == True:
        axes.set_xscale('log')
    
    if extra_stuff == True:
        # Create proxy handles for the legend (invisible lines with markers)
        proxy_handles = [mlines.Line2D([], [], color='black', marker=marker, linestyle='None', markersize=8)
                     for marker in markers]

        # Manually create the legend with unique temperature labels
        fig.legend(proxy_handles, list_names, loc='upper center', 
                   ncol=6, bbox_to_anchor=(0.50, 1.08), fontsize=12,frameon=True)

        # Adjust layout to create space for the legend box
        plt.subplots_adjust(top=0.85)
    
        # Save figure
        plt.savefig(picture_name, bbox_inches="tight")

    plt.show()
    return

def plot_shiftfactorsVStemperatures(Xi,Yi,logscale = False,
                                    fontsize_plot = 13, markersize_plot = 12, labelsize_plot = 12, 
                                    extra_stuff = False, picture_name = 'ShitfactorVsTemperatures.png'):
        
    """
    input:
        Xi numpy array N x 1: containing temperatures
        Yi numpy array N x 1: containing shiftfactors
    """
    
    # Set markers
    markers = ['o', '^', 'x', 's', 'P', 'h']
    
    # Design list
    list_names = ['$\mathrm{T}_1$','$\mathrm{T}_2$','$\mathrm{T}_3$','$\mathrm{T}_4$','$\mathrm{T}_5$','$\mathrm{T}_6$']

    ## Set figure
    fig,axes = plt.subplots(1,1,figsize = (12,7), tight_layout = True)
    
    ## Plot data
    axes.plot(Xi,Yi,color='black',linestyle='-',linewidth=int(markersize_plot/4))
    for i in range(0,len(Xi)):
        x, y = [Xi[i],Xi[i]], [Yi[i],Yi[i]]
        axes.plot(x,y,marker=markers[i],color='black',markersize = markersize_plot)
      
    ## Michs....        
    axes.set_xlabel('T [C$^\circ$]',fontsize=fontsize_plot)
    axes.set_ylabel("log10(a$_T$) [-]",fontsize=fontsize_plot)
    axes.tick_params(axis='both', which='major', labelsize=labelsize_plot)
    #axes.legend(loc='best', fontsize=fontsize_plot)
    axes.grid('on')
    if logscale == True:
        axes.set_yscale('log')    
        
    if extra_stuff == True:       
        # Create proxy handles for the legend (invisible lines with markers)
        proxy_handles = [mlines.Line2D([], [], color='black', marker=marker, linestyle='None', markersize=8)
                     for marker in markers]

        # Manually create the legend with unique temperature labels
        fig.legend(proxy_handles, list_names, loc='upper center', 
                   ncol=6, bbox_to_anchor=(0.50, 1.08), fontsize=12,frameon=True)

        # Adjust layout to create space for the legend box
        plt.subplots_adjust(top=0.85)
    
        # Save figure
        plt.savefig(picture_name, bbox_inches="tight")

    plt.show()
    return


def plot_pronyseries(A_i, B_i, a_T = 1.0, logscale = True, 
                                    fontsize_plot = 13, markersize_plot = 12, labelsize_plot = 12, 
                                    extra_stuff = False, picture_name = 'PronySeriesFit.png'):
    
    """
    input:
        A_i numpy array N x M: containing output data generated by local optimization routine
        B_i numpy array L x K: containing pronyseries prediction
    """
    
    # Set markers
    markers = ['o', '^', 'x', 's', 'P', 'h']
    
    # Design list
    list_names = ['$\mathrm{T}_1$','$\mathrm{T}_2$','$\mathrm{T}_3$','$\mathrm{T}_4$','$\mathrm{T}_5$','$\mathrm{T}_6$']

    ## Get all unique temperatures
    temp_unique = np.unique(A_i[:,0])
    
    ## Set data
    Z, X, Y  = A_i[:,0], A_i[:,1], A_i[:,2]
    
    ## Set data
    Xp, Yp = B_i[:,0], B_i[:,1]
    
    ## Set figure
    fig,axes = plt.subplots(1,1,figsize = (12,7), tight_layout = True)

    ## Plot data
    for i in range(0,len(temp_unique)):
        x, y = X[Z==temp_unique[i]], Y[Z==temp_unique[i]]
        axes.plot(x*a_T,y,marker=markers[i],color='black',markersize = markersize_plot)
    axes.plot(x*a_T,y,marker='none',color='black', label='shifted data')

    ## Plot prediction
    axes.plot(Xp, Yp, linestyle='-',color='red',label='prony fit',linewidth=int(markersize_plot/2))

    ## Michs....        
    axes.set_xlabel('$\omega$ [rad/s]',fontsize=fontsize_plot)
    axes.set_ylabel("$E'$ [MPa]",fontsize=fontsize_plot)
    axes.tick_params(axis='both', which='major', labelsize=labelsize_plot)
    axes.legend(loc='best', fontsize=fontsize_plot)
    axes.grid('on')
    if logscale == True:
        axes.set_xscale('log')
    
    if extra_stuff == True:
        # Create proxy handles for the legend (invisible lines with markers)
        proxy_handles = [mlines.Line2D([], [], color='black', marker=marker, linestyle='None', markersize=8)
                     for marker in markers]

        # Manually create the legend with unique temperature labels
        fig.legend(proxy_handles, list_names, loc='upper center', 
                   ncol=6, bbox_to_anchor=(0.50, 1.08), fontsize=12,frameon=True)

        # Adjust layout to create space for the legend box
        plt.subplots_adjust(top=0.85)
    
        # Save figure
        plt.savefig(picture_name, bbox_inches="tight")

    plt.show()
    return






